/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ultramotor.ui.sanPham;

import com.ultramotor.dao.NhaSanXuatDAO;
import com.ultramotor.entity.NhaSanXuat;
import com.ultramotor.util.MsgBox;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author thaian
 */
public class NhaSanXuatPanel extends javax.swing.JPanel {
    private NhaSanXuat nsx;
    /**
     * Creates new form NhaSanXuatPanel
     */
    public NhaSanXuatPanel() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlNhaSanXuat = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTenNSX = new javax.swing.JTextField();
        txtID_NSX = new javax.swing.JTextField();
        btnThem = new com.swingx.Button();
        btnSua = new com.swingx.Button();

        pnlNhaSanXuat.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel4.setText("Nhà Sản Xuất");

        jLabel5.setText("ID_NSX");

        jLabel6.setText("Tên Nhà Sản Xuất");

        btnThem.setBackground(new java.awt.Color(0, 153, 153));
        btnThem.setText("Thêm ");

        btnSua.setBackground(new java.awt.Color(0, 153, 153));
        btnSua.setText("Sửa");

        javax.swing.GroupLayout pnlNhaSanXuatLayout = new javax.swing.GroupLayout(pnlNhaSanXuat);
        pnlNhaSanXuat.setLayout(pnlNhaSanXuatLayout);
        pnlNhaSanXuatLayout.setHorizontalGroup(
            pnlNhaSanXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNhaSanXuatLayout.createSequentialGroup()
                .addGroup(pnlNhaSanXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlNhaSanXuatLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlNhaSanXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlNhaSanXuatLayout.createSequentialGroup()
                                .addGroup(pnlNhaSanXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(txtID_NSX, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pnlNhaSanXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(txtTenNSX, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlNhaSanXuatLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlNhaSanXuatLayout.setVerticalGroup(
            pnlNhaSanXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNhaSanXuatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(pnlNhaSanXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlNhaSanXuatLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtID_NSX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlNhaSanXuatLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTenNSX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlNhaSanXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlNhaSanXuat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlNhaSanXuat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.swingx.Button btnSua;
    private com.swingx.Button btnThem;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel pnlNhaSanXuat;
    private javax.swing.JTextField txtID_NSX;
    private javax.swing.JTextField txtTenNSX;
    // End of variables declaration//GEN-END:variables
NhaSanXuatDAO dao_NSX = new NhaSanXuatDAO();
    int row = -1;
    void init(){

        this.row = -1;
        this.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentHidden(ComponentEvent ce) {
                System.out.println("Component Hidden");
            }

            @Override
            public void componentShown(ComponentEvent ce) {
                System.out.println("Component Showned");
            }

            @Override
            public void componentResized(ComponentEvent ce) {
                System.out.println("Component Resized");
                addListeners();
            }

        });
    }
    
    // Bang Nha San Xuat
    
    public NhaSanXuat getForm_NSX(){
        NhaSanXuat nsx = new NhaSanXuat();
        nsx.setIdNSX(txtID_NSX.getText());
        nsx.setTenNSX(txtTenNSX.getText());
        return nsx;
    }
    
    public void clearForm_NSX(){
        
            txtID_NSX.setText("");
            txtTenNSX.setText("");
        
        
    }
    void setFrom_NSX(){
        if (nsx== null) {
            clearForm_NSX();
            return;
        }
        txtID_NSX.setText(nsx.getIdNSX());
        txtTenNSX.setText(nsx.getTenNSX());
    }

    public void setForm_NSX(NhaSanXuat nsx) {
        this.nsx = nsx;
        setFrom_NSX();
    }
    
    private void addListeners() {
        btnSua.addActionListener((ActionEvent e) -> {
        });
        btnThem.addActionListener((ActionEvent e) -> {
        });

    }

    public void setAddNSX_Listener(ActionListener updateListener) {
        btnThem.addActionListener(updateListener);
    }
    public void setUpdateNSX_Listener(ActionListener updateListener) {
        btnSua.addActionListener(updateListener);
    }
    
}
