/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ultramotor.ui.sanPham;

import com.ultramotor.dao.DongSanPhamDAO;
import com.ultramotor.dao.SanPhamDAO;
import com.ultramotor.entity.ModelSanPham;
import com.ultramotor.entity.SanPham;
import com.ultramotor.util.MsgBox;
import com.ultramotor.util.XImage;
import java.util.HashSet;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author thaian
 */
public class sanpham extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public sanpham() {
        initComponents();
        fillTableSP();
        this.row = -1;
        fillComboVaiTro();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pblSP = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMoTa = new javax.swing.JTextArea();
        btnLuuSanPham = new javax.swing.JButton();
        lblHinh = new javax.swing.JLabel();
        btnCapNhatSP = new javax.swing.JButton();
        btnXoaSP = new com.swingx.Button();
        cboSP_IdDongSP = new com.swingx.ComboBoxSuggestion();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblSP = new com.ultramotor.component.table.Table();
        txtMaSKU = new com.swingx.TextField();
        lblVaiTro = new javax.swing.JLabel();
        txtMauSac = new com.swingx.TextField();
        txtDiaChiSX = new com.swingx.TextField();
        txtTGBH = new com.swingx.TextField();
        txtTenSP = new com.swingx.TextField();
        txtMaNV = new com.swingx.TextField();
        txtGiaTien = new com.swingx.TextField();
        txtPhanKhoi = new com.swingx.TextField();
        txtDoiXe = new com.swingx.TextField();
        lblVaiTro1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pblSP.setBackground(new java.awt.Color(255, 255, 255));

        txtMoTa.setColumns(20);
        txtMoTa.setRows(5);
        jScrollPane1.setViewportView(txtMoTa);

        btnLuuSanPham.setText("Lưu");
        btnLuuSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuSanPhamActionPerformed(evt);
            }
        });

        lblHinh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHinh.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 1, true));
        lblHinh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblHinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHinhMouseClicked(evt);
            }
        });

        btnCapNhatSP.setText("Cập nhật");
        btnCapNhatSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatSPActionPerformed(evt);
            }
        });

        btnXoaSP.setText("Xoá");

        tblSP.setForeground(new java.awt.Color(0, 153, 153));
        tblSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "SKU", "Tên SP", "Màu Sắc", "Phân Khối", "Thời gian BH", "Địa chỉ SX", "Giá Tiền", "Mô tả", "Đời xe", "Hình", "Id_DSP", "Id_NV"
            }
        ));
        tblSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSPMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblSP);

        txtMaSKU.setLabelText("SKU");

        lblVaiTro.setForeground(new java.awt.Color(102, 102, 102));
        lblVaiTro.setText("ID_Model");

        txtMauSac.setLabelText("Màu Sắc");

        txtDiaChiSX.setLabelText("Địa chỉ SX");

        txtTGBH.setLabelText("TGBH");

        txtTenSP.setLabelText("Tên SP");

        txtMaNV.setLabelText("Mã NV");

        txtGiaTien.setLabelText("Giá Tiền");

        txtPhanKhoi.setLabelText("Phân Khối");

        txtDoiXe.setLabelText("Đời xe");

        lblVaiTro1.setForeground(new java.awt.Color(102, 102, 102));
        lblVaiTro1.setText("Mô tả");

        javax.swing.GroupLayout pblSPLayout = new javax.swing.GroupLayout(pblSP);
        pblSP.setLayout(pblSPLayout);
        pblSPLayout.setHorizontalGroup(
            pblSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pblSPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pblSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pblSPLayout.createSequentialGroup()
                        .addGroup(pblSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtTGBH, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                            .addComponent(lblVaiTro, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboSP_IdDongSP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaSKU, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtMauSac, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDiaChiSX, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                        .addGroup(pblSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pblSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtPhanKhoi, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                                .addComponent(txtGiaTien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtTenSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtMaNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(txtDoiXe, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pblSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pblSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblHinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblVaiTro1)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE))
                            .addGroup(pblSPLayout.createSequentialGroup()
                                .addComponent(btnLuuSanPham)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCapNhatSP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnXoaSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane4))
                .addContainerGap())
        );
        pblSPLayout.setVerticalGroup(
            pblSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pblSPLayout.createSequentialGroup()
                .addGroup(pblSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pblSPLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pblSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMaSKU, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pblSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pblSPLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(lblVaiTro)
                                .addGap(18, 18, 18)
                                .addComponent(cboSP_IdDongSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtMauSac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pblSPLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtGiaTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pblSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pblSPLayout.createSequentialGroup()
                                .addComponent(txtPhanKhoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDoiXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pblSPLayout.createSequentialGroup()
                                .addComponent(txtDiaChiSX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTGBH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pblSPLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lblHinh, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(lblVaiTro1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addGroup(pblSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLuuSanPham)
                            .addComponent(btnCapNhatSP)
                            .addComponent(btnXoaSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(19, 19, 19)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pblSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pblSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLuuSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuSanPhamActionPerformed
        // TODO add your handling code here:
        this.insert_SP();
    }//GEN-LAST:event_btnLuuSanPhamActionPerformed

    private void btnCapNhatSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatSPActionPerformed
        // TODO add your handling code here:
        this.update_SP();
    }//GEN-LAST:event_btnCapNhatSPActionPerformed

    private void lblHinhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHinhMouseClicked
        // TODO add your handling code here:
        XImage.uploadIcon(lblHinh);
    }//GEN-LAST:event_lblHinhMouseClicked

    private void tblSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSPMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 1) {
            this.row = tblSP.getSelectedRow();
            this.edit_SP();
        }
    }//GEN-LAST:event_tblSPMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sanpham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sanpham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sanpham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sanpham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sanpham().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhatSP;
    private javax.swing.JButton btnLuuSanPham;
    private com.swingx.Button btnXoaSP;
    private com.swingx.ComboBoxSuggestion cboSP_IdDongSP;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblHinh;
    private javax.swing.JLabel lblVaiTro;
    private javax.swing.JLabel lblVaiTro1;
    private javax.swing.JPanel pblSP;
    private com.ultramotor.component.table.Table tblSP;
    private com.swingx.TextField txtDiaChiSX;
    private com.swingx.TextField txtDoiXe;
    private com.swingx.TextField txtGiaTien;
    private com.swingx.TextField txtMaNV;
    private com.swingx.TextField txtMaSKU;
    private com.swingx.TextField txtMauSac;
    private javax.swing.JTextArea txtMoTa;
    private com.swingx.TextField txtPhanKhoi;
    private com.swingx.TextField txtTGBH;
    private com.swingx.TextField txtTenSP;
    // End of variables declaration//GEN-END:variables

    SanPhamDAO dao_SP = new SanPhamDAO();
    int row = -1;

    void fillTableSP() {

        DefaultTableModel model = (DefaultTableModel) tblSP.getModel();
        model.setRowCount(0);
        try {
            List<SanPham> list = dao_SP.selectAll();
            for (SanPham sp : list) {
                Object[] row = {
                    sp.getSku(),
                    sp.getTenSP(),
                    sp.getMauSac(),
                    sp.getPhanKhoi(),
                    sp.getThoiGianBH(),
                    sp.getDiaChiSX(),
                    sp.getGiaTien(),
                    sp.getMoTa(),
                    sp.getDoiXe(),
                    sp.getHinh(),
                    sp.getIdDongSP(),
                    sp.getIdNV()
                };
                model.addRow(row);
            }
        } catch (Exception e) {
            e.printStackTrace();
            MsgBox.inform("Lỗi truy vấn dữ liệu!");
        }
    }

    private void fillComboVaiTro() {
        HashSet<String> set = new HashSet();
        new DongSanPhamDAO().selectAll().forEach((dsp) -> {
            set.add(dsp.getIdDongSP());
        });
        cboSP_IdDongSP.setModel(new DefaultComboBoxModel(set.toArray()));
    }

    void insert_SP() {
        SanPham model = getForm_SP();
        try {
            dao_SP.insert(model);
            fillTableSP();

            this.clearForm_SP();
            MsgBox.inform("Thêm mới thành công!");
        } catch (Exception e) {
            e.printStackTrace();
            MsgBox.inform("Thêm mới thất bại!");
        }
    }

    void update_SP() {
        SanPham model = getForm_SP();
        try {
            dao_SP.update(model);
            fillTableSP();
            clearForm_SP();
            MsgBox.inform("Cập nhật thành công!");
        } catch (Exception e) {
            e.printStackTrace();
            MsgBox.inform("Cập nhật thất bại!");
        }
    }

    void delete_SP() {

        String maSKU = txtMaSKU.getText();
        try {
            dao_SP.delete(maSKU);
            this.fillTableSP();
            this.clearForm_SP();
            MsgBox.inform("Xóa thành công!");
        } catch (Exception e) {
            e.printStackTrace();
            MsgBox.inform("Xoá thất bại");
        }

    }

    SanPham getForm_SP() {
        SanPham sp = new SanPham();
        sp.setSku(txtMaSKU.getText());
        sp.setTenSP(txtTenSP.getText());
        sp.setMauSac(txtMauSac.getText());
        sp.setPhanKhoi(txtPhanKhoi.getText());
        sp.setThoiGianBH(Integer.valueOf(txtTGBH.getText()));
        sp.setDiaChiSX(txtDiaChiSX.getText());
        sp.setGiaTien(Double.valueOf(txtGiaTien.getText()));
        sp.setMoTa(txtMoTa.getText());
        sp.setDoiXe(Integer.valueOf(txtDoiXe.getText()));
        sp.setHinh(lblHinh.getToolTipText());
        sp.setIdDongSP((String) cboSP_IdDongSP.getSelectedItem());
        sp.setIdNV(txtMaNV.getText());
        return sp;
    }

    void clearForm_SP() {
        txtMaSKU.setText("");
        txtTenSP.setText("");
        txtMauSac.setText("");
        txtPhanKhoi.setText("");
        txtTGBH.setText("");
        txtDiaChiSX.setText("");
        txtGiaTien.setText("");
        txtMoTa.setText("");
        txtDoiXe.setText("");
        cboSP_IdDongSP.setSelectedIndex(0);
        txtMaNV.setText("");
        XImage.setIcon(XImage.read("default.png"), lblHinh);
    }

    void setForm_SP(SanPham sp) {
        txtMaSKU.setText(sp.getSku());
        txtTenSP.setText(sp.getTenSP());
        txtMauSac.setText(sp.getMauSac());
        txtPhanKhoi.setText(sp.getPhanKhoi());
        txtTGBH.setText(String.valueOf(sp.getThoiGianBH()));
        txtDiaChiSX.setText(sp.getDiaChiSX());
        txtGiaTien.setText(String.valueOf(sp.getGiaTien()));
        txtMoTa.setText(sp.getMoTa());
        txtDoiXe.setText(String.valueOf(sp.getDoiXe()));
        if (sp.getHinh() != null) {
            XImage.setIcon(XImage.read(sp.getHinh()), lblHinh);
        }

        cboSP_IdDongSP.setSelectedItem(sp.getIdDongSP());
        txtMaNV.setText(sp.getIdNV());
    }

    void edit_SP() {
        String maSKU = (String) tblSP.getValueAt(this.row, 0);
        SanPham sp = dao_SP.selectByID(maSKU);
        this.setForm_SP(sp);
//        showCard("SP");
    }
}
