/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ultramotor.ui.hoadon;

import com.ultramotor.component.table.ModelAction;
import com.ultramotor.component.table.ModelEvent;
import com.ultramotor.dao.DichVuDAO;
import com.ultramotor.dao.HoaDonDAO;
import com.ultramotor.dao.KhachHangDAO;
import com.ultramotor.dao.SanPhamDAO;
import com.ultramotor.entity.ChiTietHoaDon;
import com.ultramotor.entity.DichVu;
import com.ultramotor.entity.HoaDon;
import com.ultramotor.entity.KhachHang;
import com.ultramotor.entity.NhanVien;
import com.ultramotor.entity.SanPham;
import com.ultramotor.util.Auth;
import com.ultramotor.util.MsgBox;
import com.ultramotor.util.XDate;
import com.ultramotor.util.XImage;
import java.awt.event.ActionEvent;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author BRAVO
 */
public class HoaDonPanel extends javax.swing.JPanel {

    /**
     * Creates new form HoaDonPanel
     */
    public HoaDonPanel() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgrTrangThai = new javax.swing.ButtonGroup();
        pnlMain = new javax.swing.JPanel();
        lblQLHD = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlHoaDon = new javax.swing.JPanel();
        pnlTTDH = new javax.swing.JPanel();
        cboDonViTinh = new javax.swing.JComboBox<>();
        txtMaSP = new com.swingx.TextField();
        txtGiaBan = new com.swingx.TextField();
        txtTenSP = new com.swingx.TextField();
        lblHinh = new javax.swing.JLabel();
        pnlSanPham = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblSanPham = new com.ultramotor.component.table.Table();
        txtTimKiemSP = new com.swingx.SearchTextField();
        pnlTTC = new javax.swing.JPanel();
        txtHoTenKH = new com.swingx.TextField();
        txtDiaChi = new com.swingx.TextField();
        txtSDT = new com.swingx.TextField();
        txtMaKH = new com.swingx.TextField();
        txtTimKiemKH = new com.swingx.SearchTextField();
        pnlButton2 = new javax.swing.JPanel();
        btnLuu = new com.swingx.Button();
        btnThanhToan1 = new com.swingx.Button();
        btnReset2 = new com.swingx.Button();
        pnlTTHD = new javax.swing.JPanel();
        txtMaHD = new com.swingx.TextField();
        txtThoiGian = new com.swingx.TextField();
        cboLoaiThanhToan = new javax.swing.JComboBox<>();
        txtTrangThai = new com.swingx.TextField();
        txtMaHD3 = new com.swingx.TextField();
        pnlTBLHoaDon = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblHoaDonNgay = new com.ultramotor.component.table.Table();
        txtTimKiemHD = new com.swingx.SearchTextField();
        pnlCTHD = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblSanPham1 = new com.ultramotor.component.table.Table();
        txtTimKiemSP1 = new com.swingx.SearchTextField();
        pnlLDanhSach = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblHoaDon = new com.ultramotor.component.table.Table();
        pnlButton1 = new javax.swing.JPanel();
        btnCapNhat1 = new com.swingx.Button();
        btnReset1 = new com.swingx.Button();

        lblQLHD.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblQLHD.setForeground(new java.awt.Color(0, 153, 255));
        lblQLHD.setText("UltraMotor - Bán hàng");

        pnlHoaDon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlTTDH.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin đơn hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(0, 153, 255))); // NOI18N

        cboDonViTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));
        cboDonViTinh.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Số lượng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(102, 102, 102))); // NOI18N

        txtMaSP.setLabelText("Mã sản phẩm");
        txtMaSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaSPActionPerformed(evt);
            }
        });

        txtGiaBan.setLabelText("Giá bán");
        txtGiaBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiaBanActionPerformed(evt);
            }
        });

        txtTenSP.setLabelText("Tên sản phẩm");
        txtTenSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenSPActionPerformed(evt);
            }
        });

        lblHinh.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Hình"));

        javax.swing.GroupLayout pnlTTDHLayout = new javax.swing.GroupLayout(pnlTTDH);
        pnlTTDH.setLayout(pnlTTDHLayout);
        pnlTTDHLayout.setHorizontalGroup(
            pnlTTDHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTTDHLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTTDHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cboDonViTinh, 0, 220, Short.MAX_VALUE)
                    .addComponent(txtGiaBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTenSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtMaSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblHinh, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTTDHLayout.setVerticalGroup(
            pnlTTDHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTTDHLayout.createSequentialGroup()
                .addComponent(txtMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cboDonViTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHinh, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                .addGap(33, 33, 33))
        );

        cboDonViTinh.getAccessibleContext().setAccessibleName("Số lượng");

        pnlHoaDon.add(pnlTTDH, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, 260, 550));

        pnlSanPham.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sản phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(0, 153, 255))); // NOI18N

        tblSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "SKU", "Tên SP", "Giá tiền", "Màu sắc", "Phân khối", "Hình", "Tồn kho"
            }
        ));
        tblSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSanPhamMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblSanPham);

        javax.swing.GroupLayout pnlSanPhamLayout = new javax.swing.GroupLayout(pnlSanPham);
        pnlSanPham.setLayout(pnlSanPhamLayout);
        pnlSanPhamLayout.setHorizontalGroup(
            pnlSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSanPhamLayout.createSequentialGroup()
                .addContainerGap(204, Short.MAX_VALUE)
                .addComponent(txtTimKiemSP, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pnlSanPhamLayout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlSanPhamLayout.setVerticalGroup(
            pnlSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSanPhamLayout.createSequentialGroup()
                .addComponent(txtTimKiemSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlHoaDon.add(pnlSanPham, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 470, 540));
        pnlSanPham.getAccessibleContext().setAccessibleName("");

        pnlTTC.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin chung", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(0, 153, 255))); // NOI18N

        txtHoTenKH.setLabelText("Họ tên khách hàng");
        txtHoTenKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoTenKHActionPerformed(evt);
            }
        });

        txtDiaChi.setLabelText("Địa chỉ");
        txtDiaChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiaChiActionPerformed(evt);
            }
        });

        txtSDT.setLabelText("Số điện thoại");
        txtSDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSDTActionPerformed(evt);
            }
        });

        txtMaKH.setLabelText("Mã khách hàng");
        txtMaKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaKHActionPerformed(evt);
            }
        });

        pnlButton2.setOpaque(false);
        pnlButton2.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        btnLuu.setBackground(new java.awt.Color(113, 118, 145));
        btnLuu.setForeground(new java.awt.Color(255, 255, 255));
        btnLuu.setText("Lưu");
        btnLuu.setBorderPainted(false);
        btnLuu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });
        pnlButton2.add(btnLuu);

        btnThanhToan1.setBackground(new java.awt.Color(113, 118, 145));
        btnThanhToan1.setForeground(new java.awt.Color(255, 255, 255));
        btnThanhToan1.setText("Thanh toán");
        btnThanhToan1.setBorderPainted(false);
        btnThanhToan1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnThanhToan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhToan1ActionPerformed(evt);
            }
        });
        pnlButton2.add(btnThanhToan1);

        btnReset2.setBackground(new java.awt.Color(113, 118, 145));
        btnReset2.setForeground(new java.awt.Color(255, 255, 255));
        btnReset2.setText("Đặt lại");
        btnReset2.setBorderPainted(false);
        btnReset2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnReset2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReset2ActionPerformed(evt);
            }
        });
        pnlButton2.add(btnReset2);

        javax.swing.GroupLayout pnlTTCLayout = new javax.swing.GroupLayout(pnlTTC);
        pnlTTC.setLayout(pnlTTCLayout);
        pnlTTCLayout.setHorizontalGroup(
            pnlTTCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTTCLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTTCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtTimKiemKH, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSDT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtHoTenKH, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtMaKH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(pnlButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlTTCLayout.setVerticalGroup(
            pnlTTCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTTCLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTimKiemKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txtHoTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pnlHoaDon.add(pnlTTC, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 260, 540));

        pnlTTHD.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin hóa đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(0, 153, 255))); // NOI18N

        txtMaHD.setLabelText("Mã hóa đơn");
        txtMaHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaHDActionPerformed(evt);
            }
        });

        txtThoiGian.setLabelText("Thời gian");
        txtThoiGian.setPlaceholder("dd-MM-YYYY");

        cboLoaiThanhToan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tiền mặt", "Trả góp", "ATM" }));
        cboLoaiThanhToan.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Loại thanh toán", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(102, 102, 102))); // NOI18N

        txtTrangThai.setLabelText("Trạng thái");
        txtTrangThai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTrangThaiActionPerformed(evt);
            }
        });

        txtMaHD3.setLabelText("Mã chi tiết hóa đơn");
        txtMaHD3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaHD3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTTHDLayout = new javax.swing.GroupLayout(pnlTTHD);
        pnlTTHD.setLayout(pnlTTHDLayout);
        pnlTTHDLayout.setHorizontalGroup(
            pnlTTHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTTHDLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTTHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtMaHD3, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addGroup(pnlTTHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtTrangThai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cboLoaiThanhToan, javax.swing.GroupLayout.Alignment.LEADING, 0, 220, Short.MAX_VALUE)
                        .addComponent(txtThoiGian, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtMaHD, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        pnlTTHDLayout.setVerticalGroup(
            pnlTTHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTTHDLayout.createSequentialGroup()
                .addComponent(txtMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txtThoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboLoaiThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(txtTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMaHD3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        pnlHoaDon.add(pnlTTHD, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 10, 270, 550));

        pnlTBLHoaDon.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hóa đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(0, 153, 255))); // NOI18N

        tblHoaDonNgay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã hóa đơn", "Thời gian", "Loại thanh toán", "Giá tiền (SP + VAT)", "Trạng thái", "Mã khách hàng", "Mã nhân viên", "Mã sản phẩm"
            }
        ));
        jScrollPane7.setViewportView(tblHoaDonNgay);

        javax.swing.GroupLayout pnlTBLHoaDonLayout = new javax.swing.GroupLayout(pnlTBLHoaDon);
        pnlTBLHoaDon.setLayout(pnlTBLHoaDonLayout);
        pnlTBLHoaDonLayout.setHorizontalGroup(
            pnlTBLHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTBLHoaDonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTBLHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7)
                    .addGroup(pnlTBLHoaDonLayout.createSequentialGroup()
                        .addGap(0, 1280, Short.MAX_VALUE)
                        .addComponent(txtTimKiemHD, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlTBLHoaDonLayout.setVerticalGroup(
            pnlTBLHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTBLHoaDonLayout.createSequentialGroup()
                .addComponent(txtTimKiemHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        pnlHoaDon.add(pnlTBLHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 1650, 270));

        pnlCTHD.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chi tiết hóa đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(0, 153, 255))); // NOI18N

        tblSanPham1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "SKU", "Tên SP", "Giá tiền", "Màu sắc", "Phân khối", "Hình", "Tồn kho"
            }
        ));
        tblSanPham1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSanPham1MouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tblSanPham1);

        txtTimKiemSP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemSP1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCTHDLayout = new javax.swing.GroupLayout(pnlCTHD);
        pnlCTHD.setLayout(pnlCTHDLayout);
        pnlCTHDLayout.setHorizontalGroup(
            pnlCTHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCTHDLayout.createSequentialGroup()
                .addGroup(pnlCTHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTimKiemSP1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 2, Short.MAX_VALUE))
        );
        pnlCTHDLayout.setVerticalGroup(
            pnlCTHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCTHDLayout.createSequentialGroup()
                .addComponent(txtTimKiemSP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlHoaDon.add(pnlCTHD, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 10, 400, 540));

        jTabbedPane1.addTab("Hóa đơn", pnlHoaDon);

        tblHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ));
        jScrollPane5.setViewportView(tblHoaDon);

        pnlButton1.setOpaque(false);
        pnlButton1.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        btnCapNhat1.setBackground(new java.awt.Color(113, 118, 145));
        btnCapNhat1.setForeground(new java.awt.Color(255, 255, 255));
        btnCapNhat1.setText("Delete");
        btnCapNhat1.setBorderPainted(false);
        btnCapNhat1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCapNhat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhat1ActionPerformed(evt);
            }
        });
        pnlButton1.add(btnCapNhat1);

        btnReset1.setBackground(new java.awt.Color(113, 118, 145));
        btnReset1.setForeground(new java.awt.Color(255, 255, 255));
        btnReset1.setText("Export");
        btnReset1.setBorderPainted(false);
        btnReset1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnReset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReset1ActionPerformed(evt);
            }
        });
        pnlButton1.add(btnReset1);

        javax.swing.GroupLayout pnlLDanhSachLayout = new javax.swing.GroupLayout(pnlLDanhSach);
        pnlLDanhSach.setLayout(pnlLDanhSachLayout);
        pnlLDanhSachLayout.setHorizontalGroup(
            pnlLDanhSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLDanhSachLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLDanhSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 1716, Short.MAX_VALUE)
                    .addGroup(pnlLDanhSachLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(pnlButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlLDanhSachLayout.setVerticalGroup(
            pnlLDanhSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLDanhSachLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Danh sách", pnlLDanhSach);

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addComponent(lblQLHD)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jTabbedPane1)))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblQLHD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 860, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaHDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaHDActionPerformed

    private void txtMaSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaSPActionPerformed

    private void txtGiaBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiaBanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiaBanActionPerformed

    private void txtTenSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenSPActionPerformed

    private void txtHoTenKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoTenKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoTenKHActionPerformed

    private void txtDiaChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiaChiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiaChiActionPerformed

    private void txtSDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSDTActionPerformed

    private void btnCapNhat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhat1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCapNhat1ActionPerformed

    private void btnReset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReset1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReset1ActionPerformed

    private void tblSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSanPhamMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblSanPhamMouseClicked

    private void txtMaKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaKHActionPerformed

    private void txtTrangThaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTrangThaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTrangThaiActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnThanhToan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToan1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThanhToan1ActionPerformed

    private void btnReset2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReset2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReset2ActionPerformed

    private void txtMaHD3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaHD3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaHD3ActionPerformed

    private void tblSanPham1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSanPham1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblSanPham1MouseClicked

    private void txtTimKiemSP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemSP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimKiemSP1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgrTrangThai;
    private com.swingx.Button btnCapNhat1;
    private com.swingx.Button btnLuu;
    private com.swingx.Button btnReset1;
    private com.swingx.Button btnReset2;
    private com.swingx.Button btnThanhToan1;
    private javax.swing.JComboBox<String> cboDonViTinh;
    private javax.swing.JComboBox<String> cboLoaiThanhToan;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblHinh;
    private javax.swing.JLabel lblQLHD;
    private javax.swing.JPanel pnlButton1;
    private javax.swing.JPanel pnlButton2;
    private javax.swing.JPanel pnlCTHD;
    private javax.swing.JPanel pnlHoaDon;
    private javax.swing.JPanel pnlLDanhSach;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlSanPham;
    private javax.swing.JPanel pnlTBLHoaDon;
    private javax.swing.JPanel pnlTTC;
    private javax.swing.JPanel pnlTTDH;
    private javax.swing.JPanel pnlTTHD;
    private com.ultramotor.component.table.Table tblHoaDon;
    private com.ultramotor.component.table.Table tblHoaDonNgay;
    private com.ultramotor.component.table.Table tblSanPham;
    private com.ultramotor.component.table.Table tblSanPham1;
    private com.swingx.TextField txtDiaChi;
    private com.swingx.TextField txtGiaBan;
    private com.swingx.TextField txtHoTenKH;
    private com.swingx.TextField txtMaHD;
    private com.swingx.TextField txtMaHD3;
    private com.swingx.TextField txtMaKH;
    private com.swingx.TextField txtMaSP;
    private com.swingx.TextField txtSDT;
    private com.swingx.TextField txtTenSP;
    private com.swingx.TextField txtThoiGian;
    private com.swingx.SearchTextField txtTimKiemHD;
    private com.swingx.SearchTextField txtTimKiemKH;
    private com.swingx.SearchTextField txtTimKiemSP;
    private com.swingx.SearchTextField txtTimKiemSP1;
    private com.swingx.TextField txtTrangThai;
    // End of variables declaration//GEN-END:variables

    HoaDonDAO dao = new HoaDonDAO();
    SanPhamDAO SPDAO = new SanPhamDAO();
    KhachHangDAO KHDAO = new KhachHangDAO();
    
    int row = -1; //vị trí hàng được chọn trên table

    private void init() {
        fillTable();
        fillTableHoaDonNgay();
        fillTableSanPham();
        addListeners();
    }

    void setForm(HoaDon hd,ChiTietHoaDon cthd) {
        txtMaHD.setText(hd.getIdHD());
        txtThoiGian.setText(XDate.toString(hd.getThoiGian()));
        if (hd.getLoaiThanhToan().equals("Tiền mặt")) {
            cboLoaiThanhToan.setSelectedIndex(0);
        } else if (hd.getLoaiThanhToan().equals("Trả góp")) {
            cboLoaiThanhToan.setSelectedIndex(1);
        } else {
            cboLoaiThanhToan.setSelectedIndex(2);
        }
        txtTrangThai.setText(hd.getTrangThai());
        txtHoTenKH.setText(hd.getIdKH());

    }

    HoaDon getForm() {
        HoaDon hd = new HoaDon();
        hd.setIdHD(txtMaHD.getText());
        hd.setThoiGian(XDate.parse(txtThoiGian.getText()));
        hd.setLoaiThanhToan((String) cboLoaiThanhToan.getSelectedItem());
        hd.setTrangThai(txtTrangThai.getText());
        hd.setIdNV(Auth.user.getIdNV());
        hd.setIdKH(txtHoTenKH.getText());
        return hd;
    }

    ChiTietHoaDon getFormCTHD(){
        ChiTietHoaDon cthd = new ChiTietHoaDon();
        
        return cthd;
    }

    void insert() {
        HoaDon hd = getForm();
        try {
            dao.insert(hd);
            MsgBox.inform("Thêm mới thành công!");
            fillTableHoaDonNgay();
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    ;
    
//    void update(){
//        ChuyenDe cd = getForm();
//        try {
//            dao.update(cd);
//            this.fillTable();
//            this.clearForm();
//            MsgBox.alert(this, "Chỉnh sửa thành công!");
//        } catch (Exception e) {
//            MsgBox.alert(this, "Chỉnh sửa thất bại!");
//        }
//    };
//    
//    void delete(){
//        if(!Auth.isManager()){
//            MsgBox.alert(this,"Bạn không có quyền xóa chuyên đề!");
//        }
//            else if(MsgBox.confirm(this, "Bạn thực sự muốn xóa chuyên đề này?")){
//                try {
//                    dao.delete(txtMaCD.getText());
//                    this.fillTable();
//                    this.clearForm();
//                    MsgBox.alert(this, "Xóa thành công!");
//                } catch (Exception e) {
//                    MsgBox.alert(this, "Xóa thất bại!");
//                }
//            }
//    };
    
    void fillTableHoaDonNgay() {
        DefaultTableModel model = (DefaultTableModel) tblHoaDonNgay.getModel();
        model.setRowCount(0); // xóa tất cả các hàng trên jtable
        try {
            for (HoaDon hd : dao.selectByTime(XDate.toString(XDate.now(), "yyyy-MM-dd"))) {
                Object[] row = {
                    hd.getIdHD(), hd.getThoiGian(), hd.getLoaiThanhToan(),
                    hd.getTrangThai(), hd.getIdKH(), hd.getIdNV()
                };
                model.addRow(row);
            }
        } catch (Exception e) {
            MsgBox.error("Lỗi truy vấn dữ liệu");
        }
    }

    void fillTableSanPham() {
        DefaultTableModel model = (DefaultTableModel) tblSanPham.getModel();
        model.setRowCount(0); // xóa tất cả các hàng trên jtable
        try {
            for (SanPham e : SPDAO.selectAll()) {
                Object[] row = {
                    e.getSku(), e.getTenSP(), e.getGiaTien(), e.getMauSac(), e.getPhanKhoi(),
                    e.getHinh(), e.gettonKho()
                };
                model.addRow(row);
            }
        } catch (Exception e) {
            MsgBox.error("Lỗi truy vấn dữ liệu");
        }
    }

    void fillTable() {
        DefaultTableModel model = (DefaultTableModel) tblHoaDon.getModel();
        model.setRowCount(0); // xóa tất cả các hàng trên jtable
        try {
            for (HoaDon hd : dao.selectAll()) {
                Object[] row = {
                    hd.getIdHD(), hd.getThoiGian(), hd.getLoaiThanhToan(),
                    hd.getTrangThai(), hd.getIdKH(), hd.getIdNV()
                };
                model.addRow(row);
            }
        } catch (Exception e) {
            MsgBox.error("Lỗi truy vấn dữ liệu");
        }
    }

    void editSanPham() {
        try {
            String SKU = (String) tblSanPham.getValueAt(this.row, 0);
            SanPham sp = SPDAO.selectByID(SKU);
            setFormSanPham(sp);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    void timKiemKhachHang(){
        try {
            String keyword = txtTimKiemKH.getText();
            List<KhachHang> list = KHDAO.selectByKeyword(keyword); // đọc dữ liệu từ csdl
            for(KhachHang kh:list){
                txtMaKH.setText(kh.getIdKH());
                txtHoTenKH.setText(kh.getHoKH()+" "+kh.getTenKH());
                txtSDT.setText(kh.getSdt());
                txtDiaChi.setText(kh.getDiaChi());
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    
    void setFormSanPham(SanPham sp) {
        txtMaSP.setText(sp.getSku());
        txtTenSP.setText(sp.getTenSP());
        txtGiaBan.setText(String.valueOf(sp.getGiaTien()));
        if (sp.getHinh() != null) {
            lblHinh.setToolTipText(sp.getHinh());
            XImage.setIcon(XImage.read(sp.getHinh()), lblHinh);
        }
    }
//    
//    void fillComboBoxDichVu(){
//        try {
//            List<DichVu> list = DVDAO.selectAll();
//            cboDichVu.setModel(new DefaultComboBoxModel(list.toArray()));
//        } catch (Exception e) {
//        }
//    }

    private void addListeners() {

        btnLuu.addActionListener((ActionEvent e) -> {
            insert();
        });

        tblSanPham.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                row = tblSanPham.getSelectedRow();
                editSanPham();
                }
            
        });
        
        txtTimKiemKH.addKeyListener(new KeyAdapter() {
            public void keyReleased(KeyEvent e){
                timKiemKhachHang();
            }
});
    }

}
