/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.edusys.components;

import com.edusys.util.Auth;
import com.edusys.util.MsgBox;
import com.edusys.util.MyConstants;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JTextField;

/**
 *
 * @author nghipc
 */
public class MyOtpPanel extends javax.swing.JPanel {

    /**
     * Creates new form otpJPanel
     */
    public MyOtpPanel() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlVerifyOTP = new javax.swing.JPanel();
        pnlField = new javax.swing.JPanel();
        txt1 = new javax.swing.JTextField();
        txt2 = new javax.swing.JTextField();
        txt3 = new javax.swing.JTextField();
        txt4 = new javax.swing.JTextField();
        txt5 = new javax.swing.JTextField();
        txt6 = new javax.swing.JTextField();
        btnVerifyOTP = new javax.swing.JButton();
        lblOTP = new javax.swing.JLabel();
        lblInfo = new javax.swing.JLabel();

        setOpaque(false);

        pnlVerifyOTP.setBackground(new java.awt.Color(255, 255, 255));

        pnlField.setOpaque(false);
        pnlField.setLayout(new java.awt.GridLayout(1, 0, 15, 0));
        pnlField.add(txt1);
        pnlField.add(txt2);
        pnlField.add(txt3);
        pnlField.add(txt4);
        pnlField.add(txt5);

        txt6.setNextFocusableComponent(this);
        txt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt6ActionPerformed(evt);
            }
        });
        pnlField.add(txt6);

        btnVerifyOTP.setBackground(new java.awt.Color(150, 34, 200));
        btnVerifyOTP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnVerifyOTP.setForeground(new java.awt.Color(255, 255, 255));
        btnVerifyOTP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/img/icon/checked_24px.png"))); // NOI18N
        btnVerifyOTP.setText("Xác thực");
        btnVerifyOTP.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        btnVerifyOTP.setContentAreaFilled(false);
        btnVerifyOTP.setOpaque(true);

        lblOTP.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblOTP.setForeground(new java.awt.Color(150, 34, 200));
        lblOTP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/img/icon/security_shield_green_48px.png"))); // NOI18N
        lblOTP.setText("OTP");
        lblOTP.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        lblOTP.setIconTextGap(15);
        lblOTP.setRequestFocusEnabled(false);
        lblOTP.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        lblInfo.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblInfo.setForeground(lblOTP.getForeground());
        lblInfo.setText("Please enter the code that we sent you via email");

        javax.swing.GroupLayout pnlVerifyOTPLayout = new javax.swing.GroupLayout(pnlVerifyOTP);
        pnlVerifyOTP.setLayout(pnlVerifyOTPLayout);
        pnlVerifyOTPLayout.setHorizontalGroup(
            pnlVerifyOTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVerifyOTPLayout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(lblInfo)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlVerifyOTPLayout.createSequentialGroup()
                .addContainerGap(196, Short.MAX_VALUE)
                .addComponent(btnVerifyOTP, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(187, 187, 187))
            .addGroup(pnlVerifyOTPLayout.createSequentialGroup()
                .addGroup(pnlVerifyOTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlVerifyOTPLayout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(lblOTP, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlVerifyOTPLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(pnlField, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlVerifyOTPLayout.setVerticalGroup(
            pnlVerifyOTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVerifyOTPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblOTP, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(lblInfo)
                .addGap(18, 18, 18)
                .addComponent(pnlField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnVerifyOTP, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 522, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlVerifyOTP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 258, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlVerifyOTP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt6ActionPerformed
        // TODO add your handling code here:
        btnVerifyOTP.doClick();
    }//GEN-LAST:event_txt6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVerifyOTP;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblOTP;
    private javax.swing.JPanel pnlField;
    private javax.swing.JPanel pnlVerifyOTP;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txt3;
    private javax.swing.JTextField txt4;
    private javax.swing.JTextField txt5;
    private javax.swing.JTextField txt6;
    // End of variables declaration//GEN-END:variables
    JTextField[] fields;

    private void init() {
        fields = new JTextField[]{txt1, txt2, txt3, txt4, txt5, txt6};
        for (JTextField field : fields) {
            field.setHorizontalAlignment(JTextField.CENTER);
            field.setFont(new java.awt.Font("Segoe UI", 0, 28));
            field.setForeground(MyConstants.PURPLE_COLOR);
            field.setBorder(javax.swing.BorderFactory.createLineBorder(MyConstants.GRAY_COLOR));
            field.addKeyListener(new KeyAdapter() {
                @Override
                public void keyTyped(KeyEvent ke) {
                    char c = ke.getKeyChar();
                    int kc = ke.getKeyCode();
                    JTextField field = (JTextField) ke.getSource();
                    //luôn cho phép nút Backspace và Delete
                    if (kc == KeyEvent.VK_BACK_SPACE || kc == KeyEvent.VK_DELETE) {
                        return;
                    }
                    if (field.getSelectedText() == null && field.getText().length() != 0) {
                        ke.consume();
                    } else if (!Character.isDigit(c)) {
                        ke.consume();
                    } else {
                        field.transferFocus();

                    }

                }

            });
            field.addFocusListener(new FocusAdapter() {
                @Override
                public void focusLost(FocusEvent fe) {
                    JTextField field = (JTextField) fe.getSource();
                    if (field.getText().length() == 0) {
                        field.setBorder(javax.swing.BorderFactory.createLineBorder(MyConstants.GRAY_COLOR));
                    }
                }

                @Override
                public void focusGained(FocusEvent fe) {
                    JTextField field = (JTextField) fe.getSource();
                    if (field.getText().length() != 0) {
                        field.setSelectionStart(0);
                        field.setSelectionEnd(1);
                    }
                    field.setBorder(javax.swing.BorderFactory.createLineBorder(txt1.getForeground()));
                }

            });
        }
//        this.setBorder(txt1.getBorder());
    }

    public String getOTP() {
        StringBuilder sb = new StringBuilder();
        for (JTextField field : fields) {
            if (field.getText().equals("")) {
                field.requestFocus();
                return "";
            }
            sb.append(field.getText());
        }
        return sb.toString();
    }

    public void clear() {
        for (JTextField field : fields) {
            field.setText("");
        }
    }

    public boolean verifyOTP() {
        String otp = getOTP();
        if (otp.equals("")) {
            MsgBox.error("Vui lòng không để trống mã OTP");
            return false;
        }
        if (!otp.equals(Auth.getOTP())) {
            MsgBox.error("Mã xác thực OTP không hợp lệ");
            return false;
        }
        MsgBox.inform("Xác thực OTP thành công!");
        clear();
        return true;
    }
    
    public javax.swing.JButton getVerifyBtn(){
        return this.btnVerifyOTP;
    }
}
