package com.edusys.ui;

import com.edusys.dao.EduSysDAO;
import com.edusys.io.EduSysExport;
import com.edusys.io.EduSysImport;
import com.edusys.util.Auth;
import com.edusys.util.XImage;
import com.edusys.util.XDate;
import com.edusys.util.XListener;
import com.edusys.util.XLog;
import java.awt.Desktop;
import java.awt.event.ActionEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.IOException;
import java.util.Collections;
import java.util.Date;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JMenuItem;
import javax.swing.Timer;

/**
 *
 * @author nghipc
 */
public class EduSysFrame extends javax.swing.JFrame {

    /**
     * Creates new form EduSysFrame
     */
    public EduSysFrame() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSidebar = new javax.swing.JPanel();
        pnlProfile = new javax.swing.JPanel();
        lblUsername = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        lblAvatar = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        lblLogo = new javax.swing.JLabel();
        lblHinh = new javax.swing.JLabel();
        pnlBtn = new javax.swing.JPanel();
        btnKhoaHoc = new javax.swing.JButton();
        btnNhanVien = new javax.swing.JButton();
        btnNguoiHoc = new javax.swing.JButton();
        btnHocVien = new javax.swing.JButton();
        btnChuyenDe = new javax.swing.JButton();
        btnThongKe = new javax.swing.JButton();
        lblCornerIcon = new javax.swing.JLabel();
        pnlStatusBar = new javax.swing.JPanel();
        lblStatusIcon = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        lblCompanyInfo = new javax.swing.JLabel();
        lblClock = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        mnBar = new javax.swing.JMenuBar();
        mnuSys = new javax.swing.JMenu();
        mnuImport = new javax.swing.JMenu();
        mniImChuyenDe = new javax.swing.JMenuItem();
        mniImNguoiHoc = new javax.swing.JMenuItem();
        mniImKhoaHoc = new javax.swing.JMenuItem();
        mniImHocVien = new javax.swing.JMenuItem();
        mnuExport = new javax.swing.JMenu();
        mniExChuyenDe = new javax.swing.JMenuItem();
        mniExNguoiHoc = new javax.swing.JMenuItem();
        mniExKhoaHoc = new javax.swing.JMenuItem();
        mniExHocVien = new javax.swing.JMenuItem();
        mniExNhanVien = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        mniExThongKe = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mniChangePW = new javax.swing.JMenuItem();
        mniExit = new javax.swing.JMenuItem();
        mnuQuanLy = new javax.swing.JMenu();
        mniChuyenDe = new javax.swing.JMenuItem();
        mniKhoaHoc = new javax.swing.JMenuItem();
        mniNguoiHoc = new javax.swing.JMenuItem();
        mniHocVien = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mniNhanVien = new javax.swing.JMenuItem();
        mnuThongKe = new javax.swing.JMenu();
        mniBangDiem = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        mniLuongNguoiHoc = new javax.swing.JMenuItem();
        mniDiemChuyenDe = new javax.swing.JMenuItem();
        mniDoanhThu = new javax.swing.JMenuItem();
        mnuHelp = new javax.swing.JMenu();
        mniHuongDan = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        mniGioiThieu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("EduSys - Hệ Quản Trị Đào Tạo");

        pnlSidebar.setBackground(new java.awt.Color(55, 36, 111));

        pnlProfile.setOpaque(false);

        lblUsername.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsername.setText("NghiTV");

        lblRole.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRole.setForeground(new java.awt.Color(255, 255, 255));
        lblRole.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRole.setText("Trưởng phòng");

        lblAvatar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/img/avt_small.png"))); // NOI18N

        btnLogOut.setBackground(new java.awt.Color(102, 0, 204));
        btnLogOut.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnLogOut.setForeground(new java.awt.Color(255, 255, 255));
        btnLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/img/icon/exit_24px.png"))); // NOI18N
        btnLogOut.setText("Log out");
        btnLogOut.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 204), 1, true));
        btnLogOut.setBorderPainted(false);
        btnLogOut.setContentAreaFilled(false);
        btnLogOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogOut.setFocusPainted(false);
        btnLogOut.setFocusable(false);
        btnLogOut.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnLogOut.setIconTextGap(15);
        btnLogOut.setInheritsPopupMenu(true);
        btnLogOut.setOpaque(true);
        btnLogOut.setRequestFocusEnabled(false);
        btnLogOut.setRolloverEnabled(false);

        javax.swing.GroupLayout pnlProfileLayout = new javax.swing.GroupLayout(pnlProfile);
        pnlProfile.setLayout(pnlProfileLayout);
        pnlProfileLayout.setHorizontalGroup(
            pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProfileLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlProfileLayout.createSequentialGroup()
                        .addComponent(lblAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRole, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 4, Short.MAX_VALUE))
                    .addComponent(btnLogOut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlProfileLayout.setVerticalGroup(
            pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProfileLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAvatar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlProfileLayout.createSequentialGroup()
                        .addComponent(lblUsername)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblRole)))
                .addGap(18, 18, 18)
                .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/img/log_poly_50px.png"))); // NOI18N

        lblHinh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHinh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/img/bg-2.png"))); // NOI18N

        javax.swing.GroupLayout pnlSidebarLayout = new javax.swing.GroupLayout(pnlSidebar);
        pnlSidebar.setLayout(pnlSidebarLayout);
        pnlSidebarLayout.setHorizontalGroup(
            pnlSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblLogo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlProfile, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(lblHinh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlSidebarLayout.setVerticalGroup(
            pnlSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHinh, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlBtn.setBackground(new java.awt.Color(251, 250, 251));
        pnlBtn.setLayout(null);

        btnKhoaHoc.setBackground(new java.awt.Color(252, 221, 69));
        btnKhoaHoc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnKhoaHoc.setForeground(new java.awt.Color(255, 255, 255));
        btnKhoaHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/img/icon/syllabus_80px.png"))); // NOI18N
        btnKhoaHoc.setText("KHOÁ HỌC");
        btnKhoaHoc.setBorder(null);
        btnKhoaHoc.setContentAreaFilled(false);
        btnKhoaHoc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKhoaHoc.setFocusable(false);
        btnKhoaHoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKhoaHoc.setIconTextGap(15);
        btnKhoaHoc.setInheritsPopupMenu(true);
        btnKhoaHoc.setOpaque(true);
        btnKhoaHoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pnlBtn.add(btnKhoaHoc);
        btnKhoaHoc.setBounds(130, 266, 150, 150);

        btnNhanVien.setBackground(new java.awt.Color(255, 102, 0));
        btnNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnNhanVien.setForeground(new java.awt.Color(255, 255, 255));
        btnNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/img/icon/management_80px.png"))); // NOI18N
        btnNhanVien.setText("NHÂN VIÊN");
        btnNhanVien.setBorder(null);
        btnNhanVien.setContentAreaFilled(false);
        btnNhanVien.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNhanVien.setFocusable(false);
        btnNhanVien.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNhanVien.setIconTextGap(15);
        btnNhanVien.setInheritsPopupMenu(true);
        btnNhanVien.setOpaque(true);
        btnNhanVien.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pnlBtn.add(btnNhanVien);
        btnNhanVien.setBounds(560, 266, 150, 150);

        btnNguoiHoc.setBackground(new java.awt.Color(78, 90, 166));
        btnNguoiHoc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnNguoiHoc.setForeground(new java.awt.Color(255, 255, 255));
        btnNguoiHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/img/icon/team_80px.png"))); // NOI18N
        btnNguoiHoc.setText("NGƯỜI HỌC");
        btnNguoiHoc.setBorder(null);
        btnNguoiHoc.setContentAreaFilled(false);
        btnNguoiHoc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNguoiHoc.setFocusable(false);
        btnNguoiHoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNguoiHoc.setIconTextGap(15);
        btnNguoiHoc.setInheritsPopupMenu(true);
        btnNguoiHoc.setOpaque(true);
        btnNguoiHoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pnlBtn.add(btnNguoiHoc);
        btnNguoiHoc.setBounds(345, 54, 150, 150);

        btnHocVien.setBackground(new java.awt.Color(90, 178, 237));
        btnHocVien.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnHocVien.setForeground(new java.awt.Color(255, 255, 255));
        btnHocVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/img/icon/student_male_80px.png"))); // NOI18N
        btnHocVien.setText("HỌC VIÊN");
        btnHocVien.setBorder(null);
        btnHocVien.setContentAreaFilled(false);
        btnHocVien.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHocVien.setFocusable(false);
        btnHocVien.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHocVien.setIconTextGap(15);
        btnHocVien.setInheritsPopupMenu(true);
        btnHocVien.setOpaque(true);
        btnHocVien.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pnlBtn.add(btnHocVien);
        btnHocVien.setBounds(345, 266, 150, 150);

        btnChuyenDe.setBackground(new java.awt.Color(234, 129, 149));
        btnChuyenDe.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnChuyenDe.setForeground(new java.awt.Color(255, 255, 255));
        btnChuyenDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/img/icon/course_80px.png"))); // NOI18N
        btnChuyenDe.setText("CHUYÊN ĐỀ");
        btnChuyenDe.setBorder(null);
        btnChuyenDe.setContentAreaFilled(false);
        btnChuyenDe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChuyenDe.setFocusable(false);
        btnChuyenDe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnChuyenDe.setIconTextGap(15);
        btnChuyenDe.setInheritsPopupMenu(true);
        btnChuyenDe.setOpaque(true);
        btnChuyenDe.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pnlBtn.add(btnChuyenDe);
        btnChuyenDe.setBounds(130, 54, 150, 150);

        btnThongKe.setBackground(new java.awt.Color(127, 215, 213));
        btnThongKe.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnThongKe.setForeground(new java.awt.Color(255, 255, 255));
        btnThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/img/icon/report_file_80px.png"))); // NOI18N
        btnThongKe.setText("THỐNG KÊ");
        btnThongKe.setBorder(null);
        btnThongKe.setContentAreaFilled(false);
        btnThongKe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThongKe.setFocusable(false);
        btnThongKe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnThongKe.setIconTextGap(15);
        btnThongKe.setInheritsPopupMenu(true);
        btnThongKe.setOpaque(true);
        btnThongKe.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pnlBtn.add(btnThongKe);
        btnThongKe.setBounds(560, 54, 150, 150);

        lblCornerIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/img/corner1.gif"))); // NOI18N
        pnlBtn.add(lblCornerIcon);
        lblCornerIcon.setBounds(740, 370, 90, 90);

        pnlStatusBar.setBackground(new java.awt.Color(255, 255, 255));

        lblStatusIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStatusIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/img/icon/e-learning_20px.png"))); // NOI18N

        lblCompanyInfo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCompanyInfo.setForeground(new java.awt.Color(102, 102, 102));
        lblCompanyInfo.setText("QUẢN LÝ ĐÀO TẠO LẬP TRÌNH CITY");

        lblClock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/img/icon/alarm_clock_20px.png"))); // NOI18N

        lblTime.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTime.setForeground(new java.awt.Color(153, 153, 153));
        lblTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTime.setText("9:07:47 AM");

        javax.swing.GroupLayout pnlStatusBarLayout = new javax.swing.GroupLayout(pnlStatusBar);
        pnlStatusBar.setLayout(pnlStatusBarLayout);
        pnlStatusBarLayout.setHorizontalGroup(
            pnlStatusBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStatusBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblStatusIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCompanyInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 457, Short.MAX_VALUE)
                .addComponent(lblClock)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTime, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
            .addGroup(pnlStatusBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlStatusBarLayout.createSequentialGroup()
                    .addGap(8, 8, 8)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 821, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        pnlStatusBarLayout.setVerticalGroup(
            pnlStatusBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCompanyInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
            .addComponent(lblStatusIcon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblTime, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblClock, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlStatusBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlStatusBarLayout.createSequentialGroup()
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 35, Short.MAX_VALUE)))
        );

        mnBar.setBorder(null);
        mnBar.setBorderPainted(false);
        mnBar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnBar.setInheritsPopupMenu(true);
        mnBar.setPreferredSize(new java.awt.Dimension(218, 24));

        mnuSys.setText("Hệ thống");
        mnuSys.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        mnuImport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/img/icon/database_daily_import_16px.png"))); // NOI18N
        mnuImport.setText("Import");
        mnuImport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        mniImChuyenDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/img/icon/course_18px.png"))); // NOI18N
        mniImChuyenDe.setText("Chuyên Đề");
        mniImChuyenDe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuImport.add(mniImChuyenDe);

        mniImNguoiHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/img/icon/people_18px.png"))); // NOI18N
        mniImNguoiHoc.setText("Người Học");
        mniImNguoiHoc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuImport.add(mniImNguoiHoc);

        mniImKhoaHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/img/icon/diploma_18px.png"))); // NOI18N
        mniImKhoaHoc.setText("Khoá Học");
        mniImKhoaHoc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuImport.add(mniImKhoaHoc);

        mniImHocVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/img/icon/student_male_18px.png"))); // NOI18N
        mniImHocVien.setText("Học Viên");
        mniImHocVien.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuImport.add(mniImHocVien);

        mnuSys.add(mnuImport);

        mnuExport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/img/icon/database_daily_export_16px.png"))); // NOI18N
        mnuExport.setText("Export");
        mnuExport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        mniExChuyenDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/img/icon/course_18px.png"))); // NOI18N
        mniExChuyenDe.setText("Chuyên Đề");
        mniExChuyenDe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuExport.add(mniExChuyenDe);

        mniExNguoiHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/img/icon/people_18px.png"))); // NOI18N
        mniExNguoiHoc.setText("Người Học");
        mniExNguoiHoc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuExport.add(mniExNguoiHoc);

        mniExKhoaHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/img/icon/diploma_18px.png"))); // NOI18N
        mniExKhoaHoc.setText("Khoá Học");
        mniExKhoaHoc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuExport.add(mniExKhoaHoc);

        mniExHocVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/img/icon/student_male_18px.png"))); // NOI18N
        mniExHocVien.setText("Học Viên");
        mniExHocVien.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuExport.add(mniExHocVien);

        mniExNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/img/icon/administrator_male_18px.png"))); // NOI18N
        mniExNhanVien.setText("Nhân Viên");
        mniExNhanVien.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuExport.add(mniExNhanVien);

        jSeparator7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuExport.add(jSeparator7);

        mniExThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/img/icon/business_report_16px.png"))); // NOI18N
        mniExThongKe.setText("Thống Kê");
        mniExThongKe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuExport.add(mniExThongKe);

        mnuSys.add(mnuExport);

        jSeparator1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuSys.add(jSeparator1);

        mniChangePW.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/img/icon/change_16px.png"))); // NOI18N
        mniChangePW.setText("Đổi mật khẩu");
        mniChangePW.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuSys.add(mniChangePW);

        mniExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F10, 0));
        mniExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/img/icon/shutdown_16px.png"))); // NOI18N
        mniExit.setText("Kết thúc");
        mniExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuSys.add(mniExit);

        mnBar.add(mnuSys);

        mnuQuanLy.setText("Quản lý");
        mnuQuanLy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        mniChuyenDe.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.CTRL_MASK));
        mniChuyenDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/img/icon/course_18px.png"))); // NOI18N
        mniChuyenDe.setText("Chuyên Đề");
        mniChuyenDe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuQuanLy.add(mniChuyenDe);

        mniKhoaHoc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, java.awt.event.InputEvent.CTRL_MASK));
        mniKhoaHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/img/icon/diploma_18px.png"))); // NOI18N
        mniKhoaHoc.setText("Khoá Học");
        mniKhoaHoc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuQuanLy.add(mniKhoaHoc);

        mniNguoiHoc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, java.awt.event.InputEvent.CTRL_MASK));
        mniNguoiHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/img/icon/people_18px.png"))); // NOI18N
        mniNguoiHoc.setText("Người Học");
        mniNguoiHoc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuQuanLy.add(mniNguoiHoc);

        mniHocVien.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.CTRL_MASK));
        mniHocVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/img/icon/student_male_18px.png"))); // NOI18N
        mniHocVien.setText("Học Viên");
        mniHocVien.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuQuanLy.add(mniHocVien);

        jSeparator2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuQuanLy.add(jSeparator2);

        mniNhanVien.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, java.awt.event.InputEvent.CTRL_MASK));
        mniNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/img/icon/administrator_male_18px.png"))); // NOI18N
        mniNhanVien.setText("Nhân Viên");
        mniNhanVien.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuQuanLy.add(mniNhanVien);

        mnBar.add(mnuQuanLy);

        mnuThongKe.setText("Thống kê");
        mnuThongKe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        mniBangDiem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.SHIFT_MASK));
        mniBangDiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/img/icon/scorecard_18px.png"))); // NOI18N
        mniBangDiem.setText("Bảng điểm");
        mniBangDiem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuThongKe.add(mniBangDiem);

        jSeparator5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuThongKe.add(jSeparator5);

        mniLuongNguoiHoc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, java.awt.event.InputEvent.SHIFT_MASK));
        mniLuongNguoiHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/img/icon/crowd_18px.png"))); // NOI18N
        mniLuongNguoiHoc.setText("Lượng người học");
        mniLuongNguoiHoc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuThongKe.add(mniLuongNguoiHoc);

        mniDiemChuyenDe.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, java.awt.event.InputEvent.SHIFT_MASK));
        mniDiemChuyenDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/img/icon/exam_18px.png"))); // NOI18N
        mniDiemChuyenDe.setText("Điểm chuyên đề");
        mniDiemChuyenDe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuThongKe.add(mniDiemChuyenDe);

        mniDoanhThu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.SHIFT_MASK));
        mniDoanhThu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/img/icon/profit_18px.png"))); // NOI18N
        mniDoanhThu.setText("Doanh thu");
        mniDoanhThu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuThongKe.add(mniDoanhThu);

        mnBar.add(mnuThongKe);

        mnuHelp.setText("Trợ giúp");
        mnuHelp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        mniHuongDan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        mniHuongDan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/img/icon/help_18px.png"))); // NOI18N
        mniHuongDan.setText("Hướng dẫn");
        mniHuongDan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuHelp.add(mniHuongDan);

        jSeparator6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuHelp.add(jSeparator6);

        mniGioiThieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/img/icon/about_18px.png"))); // NOI18N
        mniGioiThieu.setText("Giới thiệu");
        mniGioiThieu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuHelp.add(mniGioiThieu);

        mnBar.add(mnuHelp);

        setJMenuBar(mnBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlSidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(pnlStatusBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlSidebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(pnlStatusBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EduSysFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                getInstance().setVisible(true);
                getFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChuyenDe;
    private javax.swing.JButton btnHocVien;
    private javax.swing.JButton btnKhoaHoc;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnNguoiHoc;
    private javax.swing.JButton btnNhanVien;
    private javax.swing.JButton btnThongKe;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JLabel lblAvatar;
    private javax.swing.JLabel lblClock;
    private javax.swing.JLabel lblCompanyInfo;
    private javax.swing.JLabel lblCornerIcon;
    private javax.swing.JLabel lblHinh;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblStatusIcon;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JMenuBar mnBar;
    private javax.swing.JMenuItem mniBangDiem;
    private javax.swing.JMenuItem mniChangePW;
    private javax.swing.JMenuItem mniChuyenDe;
    private javax.swing.JMenuItem mniDiemChuyenDe;
    private javax.swing.JMenuItem mniDoanhThu;
    private javax.swing.JMenuItem mniExChuyenDe;
    private javax.swing.JMenuItem mniExHocVien;
    private javax.swing.JMenuItem mniExKhoaHoc;
    private javax.swing.JMenuItem mniExNguoiHoc;
    private javax.swing.JMenuItem mniExNhanVien;
    private javax.swing.JMenuItem mniExThongKe;
    private javax.swing.JMenuItem mniExit;
    private javax.swing.JMenuItem mniGioiThieu;
    private javax.swing.JMenuItem mniHocVien;
    private javax.swing.JMenuItem mniHuongDan;
    private javax.swing.JMenuItem mniImChuyenDe;
    private javax.swing.JMenuItem mniImHocVien;
    private javax.swing.JMenuItem mniImKhoaHoc;
    private javax.swing.JMenuItem mniImNguoiHoc;
    private javax.swing.JMenuItem mniKhoaHoc;
    private javax.swing.JMenuItem mniLuongNguoiHoc;
    private javax.swing.JMenuItem mniNguoiHoc;
    private javax.swing.JMenuItem mniNhanVien;
    private javax.swing.JMenu mnuExport;
    private javax.swing.JMenu mnuHelp;
    private javax.swing.JMenu mnuImport;
    private javax.swing.JMenu mnuQuanLy;
    private javax.swing.JMenu mnuSys;
    private javax.swing.JMenu mnuThongKe;
    private javax.swing.JPanel pnlBtn;
    private javax.swing.JPanel pnlProfile;
    private javax.swing.JPanel pnlSidebar;
    private javax.swing.JPanel pnlStatusBar;
    // End of variables declaration//GEN-END:variables

    private JDialog chuyenDe;
    private JDialog khoaHoc;
    private JDialog nguoiHoc;
    private JDialog hocVien;
    private JDialog nhanVien;
    private JDialog about;
    private ChangePWJDialog changePW;
    private ThongKeJDialog thongKe;
    private static final EduSysFrame FRAME = new EduSysFrame();

    //trả về frame mặc định
    public static EduSysFrame getFrame() {
        return FRAME;
    }

    //khởi tạo các thành phần khác
    private void init() {
        chuyenDe = new ChuyenDeJDialog();
        khoaHoc = new KhoaHocJDialog();
        nguoiHoc = new NguoiHocJDialog();
        hocVien = new HocVienJDialog();
        nhanVien = new NhanVienJDialog();
        thongKe = new ThongKeJDialog();
        about = new AboutJDialog(this, true);
        changePW = new ChangePWJDialog(this, true);
        new ChaoJDialog(this, true).setVisible(true);

        addListeners(); //thêm listener cho các thành phần khác
        this.setIconImage(XImage.getAppIcon()); //đặt Icon cho Frame
        setLocationRelativeTo(null); //đặt giữa màn hình
    }

    private void addListeners() {
        addMenuListeners();
        addButonListeners();

        this.addWindowListener(XListener.dialogLs);
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowOpened(WindowEvent we) {
                new Timer(100, (ActionEvent e) -> {
                    lblTime.setText(XDate.toString(new Date(), "hh:mm:ss"));
                }).start();

            }

            @Override
            public void windowClosing(WindowEvent we) {
                Auth.close();
            }

            @Override
            public void windowActivated(WindowEvent we) {
                if (Auth.user != null) {
                    lblUsername.setText(Auth.user.getMaNV());
                    lblRole.setText(Auth.user.getVaiTro() ? "Trưởng phòng" : "Nhân viên");
                }
                if (!Auth.isManager()) {
                    mnuThongKe.remove(mniDoanhThu);
                }
            }
        });
    }

    //mở file hướng dẫn
    private void openHuongDan() {
        try {
            Desktop.getDesktop().browse(new File("help/index.html").toURI());
        } catch (IOException ex) {
            XLog.saveLog(ex.getMessage());
        }
    }

    //thêm listener cho menu bar
    private void addMenuListeners() {
        for (int i = 0; i < mnBar.getMenuCount(); i++) {
            for (int j = 0; j < mnBar.getMenu(i).getItemCount(); j++) {
                JMenuItem item = mnBar.getMenu(i).getItem(j);
                //skip the separator items
                if (item == null) {
                    continue;
                }

                item.addActionListener((ActionEvent e) -> {
                    switch (e.getActionCommand()) {
                        case "Đổi mật khẩu":
                            changePW.showCard("CurrentPW");
                            break;
                        case "Kết thúc":
                            Auth.close();
                            break;
                        case "Chuyên Đề":
                            chuyenDe.setVisible(true);
                            break;
                        case "Khoá Học":
                            khoaHoc.setVisible(true);
                            break;
                        case "Người Học":
                            nguoiHoc.setVisible(true);
                            break;
                        case "Học Viên":
                            hocVien.setVisible(true);
                            break;
                        case "Nhân Viên":
                            nhanVien.setVisible(true);
                            break;
                        case "Bảng điểm":
                            thongKe.showTab(0);
                            break;
                        case "Lượng người học":
                            thongKe.showTab(1);
                            break;
                        case "Điểm chuyên đề":
                            thongKe.showTab(2);
                            break;
                        case "Doanh thu":
                            thongKe.showTab(3);
                            break;
                        case "Hướng dẫn":
                            openHuongDan();
                            break;
                        case "Giới thiệu":
                            about.setVisible(true);
                            break;
                    }
                });
            }
        }

        addMenuInputOutput(); //thêm listener cho menu Import Export
    }

    //thêm listener cho menu Import Export
    private void addMenuInputOutput() {
        //thêm listener cho menu Import
        for (int i = 0; i < mnuImport.getItemCount(); i++) {
            JMenuItem item = mnuImport.getItem(i);
            //skip the separator items
            if (item == null) {
                continue;
            }

            item.addActionListener((ActionEvent e) -> {
                File file = EduSysImport.showOpenDialog(); //mở hộp thoại chọn file dữ liệu
                switch (e.getActionCommand()) {
                    case "Chuyên Đề":
                        EduSysImport.importChuyenDe(file);
                        break;
                    case "Khoá Học":
                        EduSysImport.importKhoaHoc(file);
                        break;
                    case "Người Học":
                        EduSysImport.importNguoiHoc(file);
                        break;
                    case "Học Viên":
                        EduSysImport.importHocVien(file);
                        break;
                }
            });
        }

        //thêm listener cho menu export
        for (int i = 0; i < mnuExport.getItemCount(); i++) {
            JMenuItem item = mnuExport.getItem(i);
            //skip the separator items
            if (item == null) {
                continue;
            }

            item.addActionListener((ActionEvent e) -> {
                File file = EduSysExport.showSaveDialog(e.getActionCommand()); //mở hộp thoại chọn file save dữ liệu
                if (file == null) {
                    return;
                }

                if (e.getActionCommand().equals("Thống Kê")) { //nếu là export thống kê
                    EduSysExport.exportAllThongKEe(file, Auth.isManager());
                    return;
                }

                List list = Collections.EMPTY_LIST;
                switch (e.getActionCommand()) {
                    case "Chuyên Đề":
                        list = EduSysDAO.CHUYEN_DE_DAO.selectAll();
                        break;
                    case "Khoá Học":
                        list = EduSysDAO.KHOA_HOC_DAO.selectAll();
                        break;
                    case "Người Học":
                        list = EduSysDAO.NGUOI_HOC_DAO.selectAll();
                        break;
                    case "Học Viên":
                        list = EduSysDAO.HOC_VIEN_DAO.selectAll();
                        break;
                    case "Nhân Viên":
                        list = EduSysDAO.NHAN_VIEN_DAO.selectAll();
                        break;
                }
                EduSysExport.exportList(list, e.getActionCommand(), file, "Default"); //xuất dữ liệu 
            });
        }
    }

    //thêm listener cho các button trong pnlBtn
    private void addButonListeners() {
        for (java.awt.Component comp : pnlBtn.getComponents()) {
            //bỏ qua các thành phần không phải là JButton
            if (!(comp instanceof javax.swing.JButton)) {
                continue;
            }

            javax.swing.JButton btn = (javax.swing.JButton) comp;
            btn.addActionListener((ActionEvent e) -> {
                switch (e.getActionCommand()) {
                    case "CHUYÊN ĐỀ":
                        chuyenDe.setVisible(true);
                        break;
                    case "KHOÁ HỌC":
                        khoaHoc.setVisible(true);
                        break;
                    case "NGƯỜI HỌC":
                        nguoiHoc.setVisible(true);
                        break;
                    case "HỌC VIÊN":
                        hocVien.setVisible(true);
                        break;
                    case "THỐNG KÊ":
                        thongKe.showTab(0);
                        break;
                    case "NHÂN VIÊN":
                        nhanVien.setVisible(true);
                        break;
                    case "HƯỚNG DẪN":
                        openHuongDan();
                        break;
                }
            });
        }
        
        //thêm listener cho btnLogout
        btnLogOut.addActionListener((ActionEvent e) -> {
            Auth.clear(); //xoá phiên đăng nhập
            this.dispose(); //đóng frame
            DangNhapJDialog.getDialog().showCard("Signin"); //hiện hộp thoại đăng nhập
        });
    }

}
