drop DATABASE IF EXISTS HONDA
go

CREATE DATABASE HONDA
go

use HONDA
go

CREATE table NHANVIEN(
    MANV NVARCHAR(10) PRIMARY KEY NOT NULL,
    HONV NVARCHAR(20) NOT NULL,
    TENNV NVARCHAR(20) NOT NULL,
    NGAYSINH DATE NOT NULL,
    GIOITINH BIT NOT NULL,
    DIACHI NVARCHAR(255) NOT NULL,
    SDT NVARCHAR(20) NOT NULL,
    EMAIL NVARCHAR(50) NOT NULL,
    LUONG FLOAT NOT NULL,
    HINH NVARCHAR(50) NOT NULL,
    VAITRO NVARCHAR(20) NOT NULL,
    MATKHAU NVARCHAR(20) NOT NULL,
    GHICHU NVARCHAR(255) NOT NULL,
)
GO

CREATE TABLE KHACHHANG(
    MAKH NVARCHAR(10) NOT NULL PRIMARY KEY,
    HOKH NVARCHAR(20) NOT NULL,
    TENKH NVARCHAR(20) NOT NULL,
    GIOITINH BIT,
    NGAYSINH DATE NOT NULL,
    DIACHI NVARCHAR(255) NOT NULL,
    SDT NVARCHAR(20) NOT NULL,
    EMAIL NVARCHAR(50) NOT NULL,
    THANHVIEN NVARCHAR(10) NOT NULL,
    GHICHU NVARCHAR(255) NOT NULL,
    MANV NVARCHAR(10),
    CONSTRAINT fk_NhanVien_KhachHang FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
)
GO 

CREATE TABLE LOAIHANG(
    MALH NVARCHAR(20) NOT NULL PRIMARY KEY,
    TENLOAIHANG NVARCHAR(255) NOT NULL 
)
GO

CREATE TABLE NHASANXUAT(
    MANSX NVARCHAR(20) NOT NULL PRIMARY KEY,
    TENNSX NVARCHAR(255) NOT NULL 
)
GO

CREATE TABLE DONGSANPHAM(
    MADONG NVARCHAR(20) NOT NULL PRIMARY KEY,
    TENDONG NVARCHAR(100) NOT NULL,
    MALH NVARCHAR(20) NOT NULL,
    MANSX NVARCHAR(20) NOT NULL,
    CONSTRAINT FK_LoaiHang_DongSanPham FOREIGN KEY (MALH) REFERENCES LOAIHANG(MALH),
    CONSTRAINT FK_NhaSanXuat_DongSanPham FOREIGN KEY (MANSX) REFERENCES NHASANXUAT(MANSX)
)
GO

CREATE TABLE SANPHAM(
    SKU NVARCHAR(20) NOT NULL PRIMARY KEY,
    TENSP NVARCHAR(100) NOT NULL,
    HINH NVARCHAR(20) NOT NULL,
    MAUSAC NVARCHAR(20) NOT NULL,
    PHANKHOI NVARCHAR(20) NOT NULL,
    TG_BAOHANH INT,
    NAMSX DATE,
    DIACHISX NVARCHAR(255) NOT NULL,
    TENNSX NVARCHAR(255) NOT NULL,
    GIATIEN FLOAT,
    MOTA NVARCHAR(255) NOT NULL,
    MADONG NVARCHAR(20) NOT NULL,
    MANV NVARCHAR(10) NOT NULL,
    CONSTRAINT FK_SanPham_NhanVien FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV),
    CONSTRAINT FK_SanPham_DongSanPham FOREIGN KEY (MADONG) REFERENCES DONGSANPHAM(MADONG)
)
GO

CREATE TABLE PHIEUXUATKHO(
    MAPX NVARCHAR(10) NOT NULL PRIMARY KEY,
    NGAYXUAT DATE NOT NULL,
    MANV NVARCHAR(10) NOT NULL,
    CONSTRAINT FK_NhanVien_PhieuXuatKho FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
)
GO

CREATE TABLE PHIEUNHAPKHO(
    MAPN NVARCHAR(10) NOT NULL PRIMARY KEY,
    NGAYNHAP DATE NOT NULL,
    MANV NVARCHAR(10) NOT NULL,
    CONSTRAINT FK_NhanVien_PhieuNhapKho FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
)
GO

CREATE TABLE CHITIETNHAPKHO(
    ID_CTNK NVARCHAR(10) NOT NULL PRIMARY KEY,
    SOLUONG INT NOT NULL,
    GIANHAP FLOAT NOT NULL,
    SKU NVARCHAR(20) NOT NULL,
    MAPN NVARCHAR(10) NOT NULL,
    CONSTRAINT FK_ChiTietNhapKho_SanPham FOREIGN KEY (SKU) REFERENCES SANPHAM(SKU),
    CONSTRAINT FK_ChiTieuNhapKho_PhieuNhapKho FOREIGN KEY (MAPN) REFERENCES PHIEUNHAPKHO(MAPN)
)
GO

CREATE TABLE CHITIETXUATKHO(
    ID_CTXK NVARCHAR(10) NOT NULL PRIMARY KEY,
    SOLUONG INT NOT NULL,
    SKU NVARCHAR(20) NOT NULL,
    MAPX NVARCHAR(10) NOT NULL,
    CONSTRAINT FK_ChiTietXuatKho_SanPham FOREIGN KEY (SKU) REFERENCES SANPHAM(SKU),
    CONSTRAINT FK_ChiTieuXuatKho_PhieuXuatKho FOREIGN KEY (MAPX) REFERENCES PHIEUXUATKHO(MAPX)
)

CREATE TABLE CHITIETSANPHAM(
    MASP NVARCHAR(10) NOT NULL PRIMARY KEY,
    SOKHUNG NVARCHAR(50) NOT NULL,
    SOMAY NVARCHAR(50) NOT NULL,
    SKU NVARCHAR(20) NOT NULL,
    ID_CTNK NVARCHAR(10) NOT NULL,
    CONSTRAINT FK_ChiTietSanPham_SanPham FOREIGN KEY (SKU) REFERENCES SANPHAM(SKU),
    CONSTRAINT FK_ChiTietSanPham_ChiTietNhapKho FOREIGN KEY (ID_CTNK) REFERENCES CHITIETNHAPKHO(ID_CTNK)
)
GO

CREATE TABLE HOADON(
    MAHD NVARCHAR(15) NOT NULL PRIMARY KEY,
    TGTAO DATE NOT NULL,
    LOAITHANHTOAN NVARCHAR(50) NOT NULL,
    TRANGTHAI NVARCHAR(10) NOT NULL,
    MANV NVARCHAR(10) NOT NULL,
    MAKH NVARCHAR(10) NOT NULL,
    CONSTRAINT FK_HoaDon_NhanVien FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MANV),
    CONSTRAINT FK_HoaDon_KhachHang FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)
)
GO

CREATE TABLE DICHVU(
    MADV NVARCHAR(10) NOT NULL PRIMARY KEY,
    TENDV NVARCHAR(255) NOT NULL,
    DONGIA FLOAT NOT NULL,
    MANV NVARCHAR(10) NOT NULL,
    CONSTRAINT FK_DichVu_NhanVien FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MANV)
)
GO

CREATE  TABLE CHITIETHOADON(
    MACTHD NVARCHAR(20) NOT NULL PRIMARY KEY,
    GIA FLOAT NOT NULL,
    MASP NVARCHAR(10) NOT NULL,
    MADV NVARCHAR(10) NOT NULL,
    MAHD NVARCHAR(15) NOT NULL,
    CONSTRAINT FK_ChiTietHoaDon_SanPham FOREIGN KEY (MASP) REFERENCES CHITIETSANPHAM(MASP),
    CONSTRAINT FK_ChiTietHoaDon_DichVu FOREIGN KEY (MADV) REFERENCES DICHVU(MADV),
    CONSTRAINT FK_ChiTietHoaDon_HoaDon FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD)
)
GO

CREATE TABLE SOBAOHANH(
    MASBH NVARCHAR(10) NOT NULL PRIMARY KEY,
    MACTHD NVARCHAR(20) NOT NULL,
    CONSTRAINT FK_SoBaoHanh_ChiTietHoaDon FOREIGN KEY (MACTHD) REFERENCES CHITIETHOADON(MACTHD)
)
GO 

CREATE TABLE CHITIETBAOHANH(
    MACTHB NVARCHAR(10) NOT NULL PRIMARY KEY,
    THOIGIANBH DATE NOT NULL,
    NOIDUNGBH NVARCHAR(255) NOT NULL,
    MANV NVARCHAR(10) NOT NULL,
    MASBH NVARCHAR(10) NOT NULL,
    CONSTRAINT FK_ChiTietBaoHanh_NhanVien FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV),
    CONSTRAINT FK_ChiTietBaoHanh_SoBaoHanh FOREIGN KEY (MASBH) REFERENCES SOBAOHANH(MASBH)
)
GO

CREATE TABLE CHITIETBAODUONG(
    MACTBD NVARCHAR(10) NOT NULL PRIMARY KEY,
    THOIGIANBD DATE NOT NULL,
    NOIDUNGBD NVARCHAR(255) NOT NULL,
    MANV NVARCHAR(10) NOT NULL,
    MASBH NVARCHAR(10) NOT NULL,
    CONSTRAINT FK_ChiTietBaoDuong_NhanVien FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV),
    CONSTRAINT FK_ChiTietBaoDuong_SoBaoHanh FOREIGN KEY (MASBH) REFERENCES SOBAOHANH(MASBH)
)
