/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ultramotor.ui;

/**
 *
 * @author Administrator
 */
public class barcodePanel extends javax.swing.JPanel {

    /**
     * Creates new form barcodePanel
     */
    public barcodePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnG1 = new javax.swing.ButtonGroup();
        btnG2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        lblMaSP = new javax.swing.JLabel();
        lblKieuBarcode = new javax.swing.JLabel();
        lblTiepDauNgu = new javax.swing.JLabel();
        lblDoDai = new javax.swing.JLabel();
        lblTaoBarcodeCho = new javax.swing.JLabel();
        cboMaSP = new javax.swing.JComboBox<>();
        rdo128 = new javax.swing.JRadioButton();
        rdoEAN13 = new javax.swing.JRadioButton();
        rdoHR = new javax.swing.JRadioButton();
        txtTiepDauNgu = new javax.swing.JTextField();
        rdoMotSP = new javax.swing.JRadioButton();
        rdoTatCa = new javax.swing.JRadioButton();
        txtDoDaiBarcode = new javax.swing.JTextField();
        lblBarcodeMau = new javax.swing.JLabel();
        btnInBarcode = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("BARCODE");

        lblMaSP.setText("Mã sản phẩm");

        lblKieuBarcode.setText("Kiểu barcode");

        lblTiepDauNgu.setText("Tiếp đầu ngữ");

        lblDoDai.setText("Độ dài barcode");

        lblTaoBarcodeCho.setText("Tạo barcode cho");

        cboMaSP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "H01", "Item 2", "Item 3", "Item 4" }));

        btnG1.add(rdo128);
        rdo128.setSelected(true);
        rdo128.setText("Code128");

        btnG1.add(rdoEAN13);
        rdoEAN13.setText("EAN13");

        btnG1.add(rdoHR);
        rdoHR.setText("CodeHR");

        txtTiepDauNgu.setText("ABC");

        btnG2.add(rdoMotSP);
        rdoMotSP.setText("Sản phẩm chưa có barcode");
        rdoMotSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoMotSPActionPerformed(evt);
            }
        });

        btnG2.add(rdoTatCa);
        rdoTatCa.setText("Tất cả");

        txtDoDaiBarcode.setText("7");

        lblBarcodeMau.setText("Barcode mẫu");

        btnInBarcode.setText("In Barcode");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBarcodeMau)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblKieuBarcode)
                                    .addGap(18, 18, 18)
                                    .addComponent(rdo128)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(rdoEAN13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(rdoHR))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblMaSP)
                                    .addGap(18, 18, 18)
                                    .addComponent(cboMaSP, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblTiepDauNgu)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtTiepDauNgu))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblTaoBarcodeCho)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(rdoMotSP)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(rdoTatCa))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblDoDai)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtDoDaiBarcode))))))
                .addContainerGap(149, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnInBarcode)
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaSP)
                    .addComponent(cboMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblKieuBarcode)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rdo128)
                        .addComponent(rdoEAN13)
                        .addComponent(rdoHR)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTiepDauNgu)
                    .addComponent(txtTiepDauNgu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDoDai)
                    .addComponent(txtDoDaiBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTaoBarcodeCho)
                    .addComponent(rdoMotSP)
                    .addComponent(rdoTatCa))
                .addGap(18, 18, 18)
                .addComponent(lblBarcodeMau)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(btnInBarcode)
                .addGap(27, 27, 27))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rdoMotSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoMotSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoMotSPActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnG1;
    private javax.swing.ButtonGroup btnG2;
    private javax.swing.JButton btnInBarcode;
    private javax.swing.JComboBox<String> cboMaSP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblBarcodeMau;
    private javax.swing.JLabel lblDoDai;
    private javax.swing.JLabel lblKieuBarcode;
    private javax.swing.JLabel lblMaSP;
    private javax.swing.JLabel lblTaoBarcodeCho;
    private javax.swing.JLabel lblTiepDauNgu;
    private javax.swing.JRadioButton rdo128;
    private javax.swing.JRadioButton rdoEAN13;
    private javax.swing.JRadioButton rdoHR;
    private javax.swing.JRadioButton rdoMotSP;
    private javax.swing.JRadioButton rdoTatCa;
    private javax.swing.JTextField txtDoDaiBarcode;
    private javax.swing.JTextField txtTiepDauNgu;
    // End of variables declaration//GEN-END:variables
}
