/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ultramotor.ui;

import com.ultramotor.util.MsgBox;

/**
 *
 * @author BRAVO
 */
public class DangNhapPanel extends javax.swing.JFrame {

    /**
     * Creates new form DangNhapPanel
     */
    public DangNhapPanel() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDangNhap1 = new javax.swing.JButton();
        pictureBox1 = new com.swingx.PictureBox();
        pwdMatKhau = new com.swingx.PasswordField();
        btnDangNhap = new com.swingx.Button();
        btnThoat = new com.swingx.Button();
        jLabel1 = new javax.swing.JLabel();
        txtTenDangNhap = new com.swingx.TextField();

        btnDangNhap1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnDangNhap1.setText("Đăng nhập");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UltraMotor - Đăng Nhập");

        pictureBox1.setImage(new javax.swing.ImageIcon(getClass().getResource("/com/ultramotor/images/LOGIN.jpg"))); // NOI18N

        pwdMatKhau.setBackground(new java.awt.Color(46, 211, 151));
        pwdMatKhau.setForeground(new java.awt.Color(255, 255, 255));
        pwdMatKhau.setCaretColor(new java.awt.Color(255, 255, 255));
        pwdMatKhau.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        pwdMatKhau.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pwdMatKhau.setLabelText("Mật khẩu");
        pwdMatKhau.setLineColor(new java.awt.Color(255, 255, 255));
        pwdMatKhau.setSelectionColor(new java.awt.Color(255, 255, 255));
        pictureBox1.add(pwdMatKhau);
        pwdMatKhau.setBounds(400, 310, 224, 48);

        btnDangNhap.setText("Đăng nhập");
        btnDangNhap.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });
        pictureBox1.add(btnDangNhap);
        btnDangNhap.setBounds(360, 440, 121, 42);

        btnThoat.setText("Thoát");
        btnThoat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });
        pictureBox1.add(btnThoat);
        btnThoat.setBounds(510, 440, 119, 43);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Quên mật khẩu?");
        pictureBox1.add(jLabel1);
        jLabel1.setBounds(510, 390, 107, 20);

        txtTenDangNhap.setAnimateLabel(true);
        txtTenDangNhap.setDrawLine(true);
        txtTenDangNhap.setLabelText("Tài khoản");
        pictureBox1.add(txtTenDangNhap);
        txtTenDangNhap.setBounds(400, 200, 220, 84);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pictureBox1, javax.swing.GroupLayout.DEFAULT_SIZE, 990, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pictureBox1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
        // TODO add your handling code here:
        Login();
    }//GEN-LAST:event_btnDangNhapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangNhapPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangNhapPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangNhapPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangNhapPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DangNhapPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.swingx.Button btnDangNhap;
    private javax.swing.JButton btnDangNhap1;
    private com.swingx.Button btnThoat;
    private javax.swing.JLabel jLabel1;
    private com.swingx.PictureBox pictureBox1;
    private com.swingx.PasswordField pwdMatKhau;
    private com.swingx.TextField txtTenDangNhap;
    // End of variables declaration//GEN-END:variables
    private void init(){
        this.setLocationRelativeTo(null);
    }
    
    private void Login(){
        String user = "admin";
        String pass = "123";
        if(txtTenDangNhap.getText().equals(user))
        {
            if(String.valueOf(pwdMatKhau.getPassword()).equals(pass)){
                MsgBox.inform("Đăng nhập thành công!");
            }
            else{
                MsgBox.error("Sai mật khẩu!");
            }
        }else{
            MsgBox.error("Sai tên đăng nhập!");
        }
    }
}
