/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.ultramotor.ui;

import com.ultramotor.dao.DongSanPhamDAO;
import com.ultramotor.dao.LoaiHangDAO;
import com.ultramotor.dao.NhaSanXuatDAO;
import com.ultramotor.entity.DongSanPham;
import com.ultramotor.entity.LoaiHang;
import com.ultramotor.entity.NhaSanXuat;
import com.ultramotor.util.MsgBox;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author thaian
 */
public class DongSanPhamPanel extends javax.swing.JPanel {

    /** Creates new form DongSanPhamPanel */
    public DongSanPhamPanel() {
        initComponents();
        init();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cboID_NSX = new javax.swing.JComboBox<>();
        cboID_LH = new javax.swing.JComboBox<>();
        txtTenDongSP = new javax.swing.JTextField();
        txtID_DongSP = new javax.swing.JTextField();
        btnThem = new com.swingx.Button();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDongSP = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel7.setText("Dòng Sản Phẩm");

        jLabel9.setText("ID_DongSP");

        jLabel8.setText("Tên Dòng SP");

        jLabel10.setText("ID_LH");

        jLabel11.setText("ID_NSX");

        cboID_NSX.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboID_NSX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboID_NSXActionPerformed(evt);
            }
        });

        cboID_LH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnThem.setBackground(new java.awt.Color(0, 153, 153));
        btnThem.setText("Thêm ");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        tblDongSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID_Dòng sản phẩm", "Tên dòng sản phẩm", "ID_LH", "ID_NSX"
            }
        ));
        jScrollPane1.setViewportView(tblDongSP);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtID_DongSP, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cboID_LH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel11)
                                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cboID_NSX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTenDongSP, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(47, 47, 47))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(txtID_DongSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8)
                    .addComponent(txtTenDongSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(cboID_LH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboID_NSX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(27, 27, 27)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cboID_NSXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboID_NSXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboID_NSXActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        this.insert();
    }//GEN-LAST:event_btnThemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.swingx.Button btnThem;
    private javax.swing.JComboBox<String> cboID_LH;
    private javax.swing.JComboBox<String> cboID_NSX;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDongSP;
    private javax.swing.JTextField txtID_DongSP;
    private javax.swing.JTextField txtTenDongSP;
    // End of variables declaration//GEN-END:variables
DongSanPhamDAO dao_DongSP = new DongSanPhamDAO();
    LoaiHangDAO dao_LH = new LoaiHangDAO();
    NhaSanXuatDAO dao_NSX = new NhaSanXuatDAO();
    void init(){
        fillTableDongSanPham();
        fillComboBoxLoaiHang();
        fillComboBoxNSX();
    }
    
    void fillComboBoxLoaiHang() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboID_LH.getModel();
        model.removeAllElements();
        List<LoaiHang> list =  dao_LH.selectAll();
        for (LoaiHang cd : list) {
            model.addElement(cd);
        }

    }
    void fillComboBoxNSX() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboID_NSX.getModel();
        model.removeAllElements();
        List<NhaSanXuat> list = dao_NSX.selectAll();
        for (NhaSanXuat cd : list) {
            model.addElement(cd);
        }

    }
    void fillTableDongSanPham() {
        DefaultTableModel model = (DefaultTableModel) tblDongSP.getModel();
        model.setRowCount(0);
        try {
            List<DongSanPham> list = dao_DongSP.selectAll();
            for (DongSanPham dsp : list) {
                Object[] row = {
                    dsp.getIdDongSP(),
                    dsp.getTenDongSP(),
                    dsp.getIdLH(),
                    dsp.getIdNSX()
                };
                model.addRow(row);
            }
        } 
        catch (Exception e) {
            e.printStackTrace();
            MsgBox.inform("Lỗi truy vấn dữ liệu!");
        }
    }
    void insert(){
        DongSanPham model = getForm();
        try {
            dao_DongSP.insert(model);
            this.fillTableDongSanPham();
            this.clearForm();
            MsgBox.inform("Thêm mới thành công!");
        } 
        catch (Exception e) {
            e.printStackTrace();
            MsgBox.inform( "Thêm mới thất bại!");
        }
    }
    DongSanPham getForm(){
        DongSanPham dsp = new DongSanPham();
        dsp.setIdDongSP(txtID_DongSP.getText());
        dsp.setTenDongSP(txtTenDongSP.getText());
        dsp.setIdLH((String) cboID_LH.getSelectedItem());
        dsp.setIdNSX((String) cboID_NSX.getSelectedItem());
        return dsp;
    }
    void clearForm(){
        DongSanPham dsp = new DongSanPham();
        this.setForm(dsp);
//        this.row = -1;
//        this.updateStatus();
    } 
     void setForm(DongSanPham dsp){
        txtID_DongSP.setText(dsp.getIdDongSP());
        txtTenDongSP.setText(dsp.getTenDongSP());
        cboID_LH.setSelectedItem(dsp.getIdLH());
        cboID_NSX.setSelectedItem(dsp.getIdNSX());
    }
}
