/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ultramotor.ui;

import com.ultramotor.dao.SanPhamDAO;
import com.ultramotor.entity.SanPham;
import com.ultramotor.util.MsgBox;
import com.ultramotor.util.XImage;
import java.util.List;
import javax.swing.Icon;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author thaian
 */
public class sanpham extends javax.swing.JFrame {
    JTable tblSP ;
    /**
     * Creates new form NewJFrame
     */
    public sanpham() {
        initComponents();
        fillTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblMaSKU = new javax.swing.JLabel();
        lblMaDong = new javax.swing.JLabel();
        lblDoixe = new javax.swing.JLabel();
        lblMauSac = new javax.swing.JLabel();
        lblTenSP = new javax.swing.JLabel();
        lblMaNV = new javax.swing.JLabel();
        lblGiatien = new javax.swing.JLabel();
        lblPhanKhoi = new javax.swing.JLabel();
        lblTGBH = new javax.swing.JLabel();
        lblDiaChiSX = new javax.swing.JLabel();
        lblMoTa = new javax.swing.JLabel();
        txtID_Model = new javax.swing.JTextField();
        txtMaSKU = new javax.swing.JTextField();
        txtDoiXe = new javax.swing.JTextField();
        txtMauSac = new javax.swing.JTextField();
        txtTenSP = new javax.swing.JTextField();
        txtMaNV = new javax.swing.JTextField();
        txtGiaTien = new javax.swing.JTextField();
        txtPhanKhoi = new javax.swing.JTextField();
        txtTGBH = new javax.swing.JTextField();
        txtDiaChiSX = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMoTa = new javax.swing.JTextArea();
        btnLuuSanPham = new javax.swing.JButton();
        lblHinh = new javax.swing.JLabel();
        btnCapNhat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblMaSKU.setText("Mã SKU");

        lblMaDong.setText("ID_Model");

        lblDoixe.setText("Đời xe");

        lblMauSac.setText("Màu sắc");

        lblTenSP.setText("Tên sản phẩm");

        lblMaNV.setText("Mã nhân viên");

        lblGiatien.setText("Giá tiền");

        lblPhanKhoi.setText("Phân khối");

        lblTGBH.setText("TGBH");

        lblDiaChiSX.setText("Địa chỉ SX");

        lblMoTa.setText("Mô tả");

        txtID_Model.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtID_ModelActionPerformed(evt);
            }
        });

        txtDoiXe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDoiXeActionPerformed(evt);
            }
        });

        txtMoTa.setColumns(20);
        txtMoTa.setRows(5);
        jScrollPane1.setViewportView(txtMoTa);

        btnLuuSanPham.setText("Lưu");
        btnLuuSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuSanPhamActionPerformed(evt);
            }
        });

        lblHinh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHinh.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 1, true));
        lblHinh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnCapNhat.setText("Cập nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMaSKU)
                            .addComponent(lblMaDong)
                            .addComponent(lblMauSac)
                            .addComponent(lblDoixe)
                            .addComponent(lblDiaChiSX))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMaSKU, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                            .addComponent(txtID_Model)
                            .addComponent(txtDoiXe)
                            .addComponent(txtMauSac)
                            .addComponent(txtDiaChiSX))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblTenSP, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblGiatien)
                                    .addComponent(lblMaNV)
                                    .addComponent(lblPhanKhoi)
                                    .addComponent(lblTGBH))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMaNV)
                            .addComponent(txtTenSP)
                            .addComponent(txtGiaTien)
                            .addComponent(txtPhanKhoi)
                            .addComponent(txtTGBH, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(lblHinh, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblMoTa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 124, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnLuuSanPham)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCapNhat)
                        .addGap(204, 204, 204))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMaSKU)
                            .addComponent(txtMaSKU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTenSP)
                            .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMaDong)
                            .addComponent(txtID_Model, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMaNV)
                            .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDoixe)
                            .addComponent(txtDoiXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGiatien)
                            .addComponent(txtGiaTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMauSac)
                            .addComponent(txtMauSac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPhanKhoi)
                            .addComponent(txtPhanKhoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTGBH)
                            .addComponent(txtTGBH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDiaChiSX)
                            .addComponent(txtDiaChiSX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblHinh, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMoTa)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLuuSanPham)
                            .addComponent(btnCapNhat))))
                .addContainerGap(132, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtID_ModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtID_ModelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtID_ModelActionPerformed

    private void txtDoiXeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDoiXeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDoiXeActionPerformed

    private void btnLuuSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuSanPhamActionPerformed
        // TODO add your handling code here:
        this.insert();
    }//GEN-LAST:event_btnLuuSanPhamActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCapNhatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sanpham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sanpham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sanpham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sanpham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sanpham().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnLuuSanPham;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDiaChiSX;
    private javax.swing.JLabel lblDoixe;
    private javax.swing.JLabel lblGiatien;
    private javax.swing.JLabel lblHinh;
    private javax.swing.JLabel lblMaDong;
    private javax.swing.JLabel lblMaNV;
    private javax.swing.JLabel lblMaSKU;
    private javax.swing.JLabel lblMauSac;
    private javax.swing.JLabel lblMoTa;
    private javax.swing.JLabel lblPhanKhoi;
    private javax.swing.JLabel lblTGBH;
    private javax.swing.JLabel lblTenSP;
    private javax.swing.JTextField txtDiaChiSX;
    private javax.swing.JTextField txtDoiXe;
    private javax.swing.JTextField txtGiaTien;
    private javax.swing.JTextField txtID_Model;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtMaSKU;
    private javax.swing.JTextField txtMauSac;
    private javax.swing.JTextArea txtMoTa;
    private javax.swing.JTextField txtPhanKhoi;
    private javax.swing.JTextField txtTGBH;
    private javax.swing.JTextField txtTenSP;
    // End of variables declaration//GEN-END:variables

     SanPhamDAO dao_SP = new SanPhamDAO();

    void fillTable() {
        DefaultTableModel model = (DefaultTableModel) tblSP.getModel();
        model.setRowCount(0);
        try {
            List<SanPham> list = dao_SP.selectAll();
            for (SanPham sp : list) {
                Object[] row = {
                    sp.getSku(),
                    sp.getTenSP(),
                    sp.getDiaChiSX(),
                    sp.getGiaTien(),
                    sp.getMauSac(),
                    sp.getThoiGianBH(),
                    sp.getMoTa(),
                    sp.getIdNV(),
                    sp.getIdModel(),
                    sp.getPhanKhoi(),
                    sp.getHinh()
                };
                model.addRow(row);
            }
        } 
        catch (Exception e) {
            e.printStackTrace();
            MsgBox.inform("Lỗi truy vấn dữ liệu!");
        }
    }
    void insert(){
        SanPham model = getForm();
        try {
            dao_SP.insert(model);
            this.fillTable();
            this.clearForm();
            MsgBox.inform("Thêm mới thành công!");
        } 
        catch (Exception e) {
            e.printStackTrace();
            MsgBox.inform( "Thêm mới thất bại!");
        }
    }
    SanPham getForm(){
        SanPham sp = new SanPham();
        sp.setSku(txtMaSKU.getText());
        sp.setTenSP(txtTenSP.getText());
        sp.setDiaChiSX(txtDiaChiSX.getText());
        sp.setGiaTien(Double.valueOf(txtGiaTien.getText()));
        sp.setMauSac(txtMauSac.getText());
        sp.setThoiGianBH(Integer.valueOf(txtTGBH.getText()));
        sp.setMoTa(txtMoTa.getText());
        sp.setIdNV(txtMaNV.getText());
        sp.setIdModel(txtID_Model.getText());
        sp.setPhanKhoi(txtPhanKhoi.getText());
        sp.setHinh(lblHinh.getToolTipText());
        return sp;
    }
    void clearForm(){
        SanPham sp = new SanPham();
        this.setForm(sp);
//        this.row = -1;
//        this.updateStatus();
    } 
     void setForm(SanPham sp){
        txtMaSKU.setText(sp.getSku());
        txtTenSP.setText(sp.getTenSP());
        txtDiaChiSX.setText(sp.getDiaChiSX());
        txtGiaTien.setText(String.valueOf(sp.getGiaTien()));
        txtMauSac.setText(sp.getMauSac());
        txtTGBH.setText(String.valueOf(sp.getThoiGianBH()));
        txtMoTa.setText(sp.getMoTa());
        txtMaNV.setText(sp.getIdNV());
        txtID_Model.setText(sp.getIdModel());
        txtPhanKhoi.setText(sp.getPhanKhoi());
        if(sp.getHinh() != null){
            lblHinh.setIcon((Icon) XImage.read(sp.getHinh()));
        }
    }}
